// <auto-generated />
using System;
using Backend.Domains.User.Persistence.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Domains.User.Persistence.Sql.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250214165646_CreatePermissionsTable")]
    partial class CreatePermissionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("User")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Domains.User.Domain.Entity.PermissionDescriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("Locale", "PermissionId")
                        .IsUnique();

                    b.ToTable("PermissionDescription", "User");
                });

            modelBuilder.Entity("Backend.Domains.User.Domain.Entity.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Permission", "User");
                });

            modelBuilder.Entity("Backend.Domains.User.Domain.Entity.PermissionNameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("Locale", "PermissionId")
                        .IsUnique();

                    b.ToTable("PermissionName", "User");
                });

            modelBuilder.Entity("Backend.Domains.User.Domain.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Hash")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsInitialUser")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("State <> 'Deleted'");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("State <> 'Deleted'");

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique()
                        .HasFilter("State <> 'Deleted'");

                    b.ToTable("Users", "User");
                });

            modelBuilder.Entity("Backend.Domains.User.Domain.Entity.PermissionDescriptionEntity", b =>
                {
                    b.HasOne("Backend.Domains.User.Domain.Entity.PermissionEntity", null)
                        .WithMany("LocalizedDescriptions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domains.User.Domain.Entity.PermissionNameEntity", b =>
                {
                    b.HasOne("Backend.Domains.User.Domain.Entity.PermissionEntity", null)
                        .WithMany("LocalizedNames")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domains.User.Domain.Entity.PermissionEntity", b =>
                {
                    b.Navigation("LocalizedDescriptions");

                    b.Navigation("LocalizedNames");
                });
#pragma warning restore 612, 618
        }
    }
}
