services:
  backend-backend:
    depends_on:
      redis:
        condition: service_healthy
        required: true
    hostname: backend
    image: inventarisierung:dev
    build:
      context: ..
      dockerfile: src/Backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - server_type=backend
      - hangfire_redis_server=redis
      - hangfire_redis_port=6379
      - hangfire_redis_database=0
      - "hangfire_redis_prefix=inventarisierung:prefix:"
      - jwt_issuer=inventarisierung
      - jwt_audience=inventarisierung
      - jwt_key=<key>
    ports:
      - "80:80"
  backend-server:
    depends_on:
      redis:
        condition: service_healthy
        required: true
    hostname: backend
    image: inventarisierung:dev
    build:
      context: ..
      dockerfile: src/Backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - server_type=server
      - hangfire_redis_server=redis
      - hangfire_redis_port=6379
      - hangfire_redis_database=0
      - "hangfire_redis_prefix=inventarisierung:prefix:"
      - jwt_issuer=inventarisierung
      - jwt_audience=inventarisierung
      - jwt_key=<key>
    labels:
      com.jetbrains.rider.debug: "false"
  backend-worker:
    depends_on:
      redis:
        condition: service_healthy
        required: true
    hostname: backend
    image: inventarisierung:dev
    build:
      context: ..
      dockerfile: src/Backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - server_type=worker
      - hangfire_redis_server=redis
      - hangfire_redis_port=6379
      - hangfire_redis_database=0
      - "hangfire_redis_prefix=inventarisierung:prefix:"
      - jwt_issuer=inventarisierung
      - jwt_audience=inventarisierung
      - jwt_key=<key>
  redis:
    hostname: redis
    image: redis:8.0-M03-alpine3.21
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping", "|" , "grep", "PONG" ]
      interval: 2s
      timeout: 1s
      retries: 20

volumes:
  redis: